// Handskriven, verifierad lista — se metodik-avsnittet i
// content/articles/en/surfable-wave-pools-world.md för källor och datum.
// Endast anläggningar som är i drift idag (inte under byggnation/planerade).

import type { WavePool } from './types';

export const verifiedWavePools: WavePool[] = [
  {
    id: 'surf-ranch',
    name: 'Surf Ranch (Kelly Slater Wave Co.)',
    location: 'Lemoore, California, USA',
    city: 'Lemoore',
    country: 'USA',
    region: 'North America',
    technology: 'Kelly Slater Wave Co. (hydrofoil pulled along a rail in a freshwater lagoon)',
    difficulty: 'Fully adjustable — the same lagoon runs everything from soft rollers to full, rifling barrels',
    description:
      "The original: an inland freshwater lagoon in California's Central Valley that produces the longest, most consistently perfect man-made wave in the sport, host to the WSL's Freshwater Pro. Public access is far more limited than the other parks on this list — sessions run through the KS Wave Co. Access Pass program and events rather than casual walk-in booking.",
    website: 'kswaveco.com',
    bookingUrl: 'https://www.kswaveco.com/',
    note: 'Invite/access-pass and event-based — not a walk-in surf park'
  },
  {
    id: 'waco-surf',
    name: 'Waco Surf (BSR Surf Resort)',
    location: 'Waco, Texas, USA',
    city: 'Waco',
    country: 'USA',
    region: 'North America',
    technology: 'American Wave Machines PerfectSwell',
    difficulty: 'Beginner whitewater through advanced barrels, with the swell direction and size rider-selectable per session',
    description:
      "A cable-park-turned-surf-resort in central Texas, one of the longest-running PerfectSwell installations and a regular stop for pro-level training camps.",
    website: 'wacosurf.com',
    bookingUrl: 'https://wacosurf.com/',
    note: null
  },
  {
    id: 'skudin-surf-american-dream',
    name: 'Skudin Surf at American Dream',
    location: 'East Rutherford, New Jersey, USA',
    city: 'East Rutherford',
    country: 'USA',
    region: 'North America',
    technology: 'American Wave Machines PerfectSwell',
    difficulty: 'Beginner-focused — built around lessons, with progression sessions for more experienced surfers',
    description:
      'A surf school-run pool inside the American Dream mega-mall, aimed squarely at first-timers and East Coast surfers with no ocean access nearby.',
    website: 'skudinsurfamericandream.com',
    bookingUrl: 'https://www.skudinsurfamericandream.com/',
    note: null
  },
  {
    id: 'dsrt-surf',
    name: 'DSRT Surf',
    location: 'Palm Desert, California, USA',
    city: 'Palm Desert',
    country: 'USA',
    region: 'North America',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner, intermediate and advanced zones run simultaneously across the lagoon',
    description: 'A desert resort build around a 52-module Wavegarden Cove lagoon, part of a larger residential/hospitality development east of Palm Springs.',
    website: 'dsrtsurf.com',
    bookingUrl: 'https://www.dsrtsurf.com/',
    note: 'Newly opened — public sessions began September 26, 2026'
  },
  {
    id: 'palm-springs-surf-club',
    name: 'Palm Springs Surf Club',
    location: 'Palm Springs, California, USA',
    city: 'Palm Springs',
    country: 'USA',
    region: 'North America',
    technology: 'Surf Loch',
    difficulty: 'Beginner to intermediate',
    description:
      'A long-running desert wave pool site (formerly Wet’n’Wild Palm Springs) rebuilt around Surf Loch wave technology, leaning toward lessons and family sessions.',
    website: 'palmspringssurfclub.com',
    bookingUrl: 'https://palmspringssurfclub.com/',
    note: null
  },
  {
    id: 'atlantic-park-surf',
    name: 'Atlantic Park Surf',
    location: 'Virginia Beach, Virginia, USA',
    city: 'Virginia Beach',
    country: 'USA',
    region: 'North America',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced, across a 46-module lagoon',
    description:
      "North America's first Wavegarden Cove, anchoring a beachfront entertainment district built by Venture Realty and Pharrell Williams's foundation.",
    website: 'atlanticparksurf.com',
    bookingUrl: 'https://atlanticparksurf.com/surf',
    note: null
  },
  {
    id: 'lost-shore-surf-resort',
    name: 'Lost Shore Surf Resort',
    location: 'Ratho, Edinburgh, Scotland, UK',
    city: 'Edinburgh',
    country: 'UK',
    region: 'Europe',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced, 52-module lagoon',
    description: "Europe's largest inland wave pool, built into a former quarry on the western edge of Edinburgh — surfing, saunas and a full resort around one lagoon.",
    website: 'lostshore.com',
    bookingUrl: 'https://www.lostshore.com/',
    note: null
  },
  {
    id: 'the-wave-bristol',
    name: 'The Wave',
    location: 'Bristol, England, UK',
    city: 'Bristol',
    country: 'UK',
    region: 'Europe',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced',
    description: "One of the first Wavegarden Cove sites in the world and the UK's best-known inland surf destination, built with sustainability and community access as explicit goals.",
    website: 'thewave.com',
    bookingUrl: 'https://www.thewave.com/',
    note: null
  },
  {
    id: 'alaia-bay',
    name: 'Alaïa Bay',
    location: 'Sion, Switzerland',
    city: 'Sion',
    country: 'Switzerland',
    region: 'Europe',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced',
    description: 'A Wavegarden Cove lagoon in the Swiss Alps, landlocked further from any coast than almost anywhere else on this list.',
    website: 'alaia.ch',
    bookingUrl: 'https://booking.alaiabay.ch/',
    note: null
  },
  {
    id: 'o2-surftown-muc',
    name: 'o2 SURFTOWN MUC',
    location: 'Hallbergmoos, near Munich, Germany',
    city: 'Munich',
    country: 'Germany',
    region: 'Europe',
    technology: 'Endless Surf (WhiteWater West)',
    difficulty: 'Explicit tiered levels from complete beginner to advanced, published on their own site',
    description: "Europe's largest wave pool by surface area, running Endless Surf's newest-generation wave technology just north of Munich.",
    website: 'surftown.de',
    bookingUrl: 'https://surftown.de/en/surf/level',
    note: null
  },
  {
    id: 'urbnsurf-melbourne',
    name: 'URBNSURF Melbourne',
    location: 'Melbourne, Australia',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Oceania',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced',
    description: "The first Wavegarden Cove in the southern hemisphere, built next to Melbourne's airport and widely credited with proving the commercial model for the whole industry.",
    website: 'urbnsurf.com',
    bookingUrl: 'https://urbnsurf.com/melbourne/',
    note: null
  },
  {
    id: 'urbnsurf-sydney',
    name: 'URBNSURF Sydney',
    location: 'Sydney, Australia',
    city: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced',
    description: "URBNSURF's second Australian site, at Sydney Olympic Park — same Wavegarden Cove technology as Melbourne.",
    website: 'urbnsurf.com',
    bookingUrl: 'https://urbnsurf.com/sydney/',
    note: null
  },
  {
    id: 'wave-park-siheung',
    name: 'Wave Park',
    location: 'Siheung, South Korea',
    city: 'Siheung',
    country: 'South Korea',
    region: 'Asia',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced, 56-module lagoon',
    description: "One of the largest Wavegarden Cove installations built, west of Seoul — reportedly built the wave-pool industry's biggest single lagoon at the time it opened.",
    website: 'wavepark.co.kr',
    bookingUrl: 'https://www.wavepark.co.kr/',
    note: null
  },
  {
    id: 'shizunami-surf-stadium',
    name: 'Shizunami Surf Stadium',
    location: 'Shizuoka, Japan',
    city: 'Shizuoka',
    country: 'Japan',
    region: 'Asia',
    technology: 'American Wave Machines PerfectSwell',
    difficulty: 'Beginner through advanced, rider-selectable',
    description: 'A PerfectSwell pool built for Olympic-level training near an existing ocean surf beach, giving Japanese surfers consistent conditions year-round.',
    website: 'surfstadium-japan.com',
    bookingUrl: 'https://surfstadium-japan.com/',
    note: null
  },
  {
    id: 'srf-park-tlv',
    name: 'SRF Park TLV',
    location: 'Tel Aviv, Israel',
    city: 'Tel Aviv',
    country: 'Israel',
    region: 'Middle East',
    technology: null,
    difficulty:
      'Explicit tiered sessions: L0 foam-wave beginner lessons, L1–L4 intermediate "surfer sessions," L5–L6 expert sessions',
    description: "Israel's first wave pool, marketed as an all-levels surf lagoon with the country's surf community behind it — wave-generation technology isn't publicly specified on their site.",
    website: 'srfparktlv.co.il',
    bookingUrl: 'https://www.srfparktlv.co.il/en/',
    note: 'Technology not publicly confirmed'
  },
  {
    id: 'al-ain-adventure',
    name: 'Al Ain Adventure (Wadi Adventure)',
    location: 'Al Ain, United Arab Emirates',
    city: 'Al Ain',
    country: 'UAE',
    region: 'Middle East',
    technology: 'Wavegarden (original/lagoon generation)',
    difficulty: 'Limited range compared to newer Cove-generation pools — mostly one wave type per session',
    description: 'One of the earliest Wavegarden installations anywhere, part of a wider adventure park in inland Abu Dhabi emirate that also runs whitewater rafting.',
    website: 'alainadventure.com',
    bookingUrl: 'https://www.alainadventure.com/',
    note: 'Older-generation Wavegarden, not the newer Cove system'
  },
  {
    id: 'beyond-the-club',
    name: 'Beyond The Club',
    location: 'São Paulo, Brazil',
    city: 'São Paulo',
    country: 'Brazil',
    region: 'South America',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced, 62-module lagoon',
    description: "Wavegarden's flagship Latin American site, built inside a large sports/lifestyle club in São Paulo rather than as a standalone resort.",
    website: 'beyondtheclub.com.br',
    bookingUrl: 'https://beyondtheclub.com.br/surf-2/',
    note: null
  },
  {
    id: 'surfland-brasil',
    name: 'Surfland Brasil',
    location: 'Garopaba, Santa Catarina, Brazil',
    city: 'Garopaba',
    country: 'Brazil',
    region: 'South America',
    technology: 'Wavegarden Cove',
    difficulty: 'Beginner through advanced',
    description: 'A Wavegarden Cove lagoon on the Santa Catarina coast, in one of Brazil’s best-known surf regions rather than an inland city.',
    website: 'surflandbrasil.com.br',
    bookingUrl: 'https://surflandbrasil.com.br/',
    note: null
  }
];
